rss:
  world:
    name: World
    icon: https://cdn-icons-png.flaticon.com/512/2240/2240692.png
    sources:
    - https://time.com/feed
    - https://feeds.bbci.co.uk/news/world/rss.xml
    notifications:
      discord: https://discord.com/api/webhooks/.../...
