rss:
  world:
    name: World
    sources:
      - https://time.com/feed/
      - https://www.theguardian.com/world/rss
      - https://feeds.bbci.co.uk/news/world/rss.xml
      - https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100727362
      - https://www.cbsnews.com/latest/rss/world
      - https://moxie.foxnews.com/google-publisher/world.xml
      - https://feeds.nbcnews.com/nbcnews/public/world
    discord_channel_id: "1315385019241595172"
    # https://about.fb.comof rchn/wp-content/uploads/2016/05/rss-urls-1.pdf

  magazine:
    name: Magazine
    sources:
      - https://www.newyorker.com/feed/news
      - https://asteriskmag.com/feed
      - https://www.nplusonemag.com/feed
      - https://feeds.feedburner.com/TheAtlanticWire
    discord_channel_id: "1327680122144297063"

  finance:
    name: Finance
    sources:
      - https://finance.yahoo.com/news/rssindex
    discord_channel_id: "1325126500336271442"

  investing:
    name: Investing
    sources:
      - https://www.investing.com/rss/news_356.rss # Company News
      - https://www.investing.com/rss/news_1065.rss # Stock Market Investment Ideas
      - https://www.investing.com/rss/news_1063.rss # Earnings Call Transcripts
      - https://www.investing.com/rss/news_1062.rss # Earnings Reports
      - https://www.globenewswire.com/AtomFeed/subjectcode/72-Press%20Releases/feedTitle/GlobeNewswire%20-%20Press%20Releases # GlobeNewswire - Press Releases
      - https://www.globenewswire.com/AtomFeed/subjectcode/29-Partnerships/feedTitle/GlobeNewswire%20-%20Partnerships # GlobeNewswire - Partnerships
      - https://www.globenewswire.com/AtomFeed/orgclass/1/feedTitle/GlobeNewswire%20-%20News%20about%20Public%20Companies # GlobeNewswire - News about Public Companies
      - https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=15839069 # CNBC - Investing
    discord_channel_id: "1325116616303837204"

  technology:
    # https://github.com/tuan3w/awesome-tech-rss
    name: Technology
    sources:
      - https://www.theverge.com/tech/rss/index.xml
      - https://9to5mac.com/feed/
      - https://9to5google.com/feed/
      - https://techcrunch.com/feed/
      - https://arstechnica.com/feed/
      - https://www.wired.com/feed/rss
      - https://www.zdnet.com/news/rss.xml
      - https://www.theregister.com/headlines.rss
      - https://boingboing.net/feed
      - https://restofworld.org/feed/latest/
      - https://www.techradar.com/rss
      - https://www.bleepingcomputer.com/feed/
      - https://feeds.feedburner.com/venturebeat/SZYF
    discord_channel_id: "1297769089024004126"

  dev:
    name: Developers
    sources:
      - https://deno.com/feed
      - https://bun.sh/rss.xml
      - https://vercel.com/atom
      - https://astro.build/rss.xml
      - https://blogs.windows.com/feed
      - https://pythoninsider.blogspot.com/rss.xml
      - https://cprss.s3.amazonaws.com/javascriptweekly.com.xml
      - https://cprss.s3.amazonaws.com/nodeweekly.com.xml
      - https://nextjs.org/feed.xml
      - https://tailwindcss.com/feeds/feed.xml
      - https://stackoverflow.blog/feed
      - https://blog.replit.com/feed.xml
      - https://supabase.com/feed.xml
      - https://netflixtechblog.com/feed
      - https://engineering.atspotify.com/feed
      - https://github.blog/feed
      - https://www.docker.com/feed
      - https://www.osnews.com/feed/
      - https://www.freecodecamp.org/news/rss
      - https://blog.google/products/chrome/rss/
      - https://blog.chromium.org/feeds/posts/default
    discord_channel_id: "1315654076280864789"

  ai:
    name: AI
    sources:
      - https://openai.com/news/rss.xml
      - https://replicate.com/blog/rss
      - https://jina.ai/feed.rss
      - https://lastweekin.ai/feed
      - https://huggingface.co/blog/feed.xml
      - https://deepmind.google/blog/rss.xml
      - https://qwenlm.github.io/blog/index.xml
      - https://blog.google/products/gemini/rss/
    discord_channel_id: "1315729383440515113"

  v2ex:
    name: V2EX
    forum: true
    language: Traditional Chinese
    sources:
      - https://www.v2ex.com/index.xml
      - https://www.v2ex.com/feed/tab/play.xml
      - https://www.v2ex.com/feed/tab/tech.xml
      - https://www.v2ex.com/feed/tab/creative.xml
    discord_channel_id: "1324024110317043742"

  free-games:
    name: "Free Games"
    importance_check: false
    sources:
      - https://www.gamerpower.com/rss/steam
      - https://www.gamerpower.com/rss/games
    discord_channel_id: "1315931763469455380"

  software:
    name: "Software"
    sources:
      - https://hnrss.org/show
      - https://www.appinn.com/feed
      - https://hellogithub.com/rss
      - https://www.producthunt.com/feed
      - https://lobste.rs/t/show
      # - https://www.reddit.com/r/SideProject/.rss
    discord_channel_id: "1326858185881026653"

  hong-kong:
    name: "Hong Kong"
    sources:
      - https://www.scmp.com/rss/2/feed
      - https://hongkongfp.com/feed/
    discord_channel_id: "1322608633355305110"

  hacker-news:
    name: "Hacker News"
    forum: true
    comment_selector: "[class='comment-tree']"
    sources:
      # - https://hnrss.org/newest
      - https://hnrss.org/frontpage
    discord_channel_id: "1320300826673156168"

  lobste-rs:
    name: "Lobste.rs"
    forum: true
    comment_selector: "[class='comments']"
    sources: # Other Categories: science, math, education
      - https://lobste.rs/t/ai.rss
      - https://lobste.rs/t/event.rss
      - https://lobste.rs/t/web.rss
      - https://lobste.rs/t/mobile.rss
      - https://lobste.rs/t/games.rss
      - https://lobste.rs/t/programming.rss
      - https://lobste.rs/t/hardware.rss
      - https://lobste.rs/t/compsci.rss
      - https://lobste.rs/t/security.rss
      - https://lobste.rs/t/privacy.rss
      - https://lobste.rs/t/release.rss
    discord_channel_id: "1320300953953505351"

  dev-to:
    name: "Dev.to"
    forum: true
    sources:
      - https://dev.to/feed
    discord_channel_id: "1320091294726488074"
