rss:
  # Source list: https://about.fb.comofrchn/wp-content/uploads/2016/05/rss-urls-1.pdf
  world:
    name: World
    description: "All over the world, except for Hong Kong, any emergency news."
    sources:
    - url: https://time.com/feed/
      scrape_needed: false
    - https://www.theguardian.com/world/rss
    - https://feeds.bbci.co.uk/news/world/rss.xml
    - https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100727362
    - https://www.cbsnews.com/latest/rss/world
    - url: https://moxie.foxnews.com/google-publisher/world.xml
      scrape_needed: false
    - https://feeds.nbcnews.com/nbcnews/public/world
    - https://www.independent.co.uk/news/world/rss
    - https://rss.dw.com/atom/rss-en-world
    - https://rss.cnn.com/rss/cnn_world.rss
    - https://abcnews.go.com/abcnews/internationalheadlines
    - https://www.aljazeera.com/xml/rss/all.xml
    - https://feeds.npr.org/1004/rss.xml
    - https://www.yahoo.com/news/rss/world/

  technology:
    name: Technology
    description: "Technology news, including software, hardware, gadgets, and any tech-related news."
    sources:
    - url: https://www.theverge.com/rss/tech/index.xml
      scrape_needed: false
    - https://www.yahoo.com/news/rss/tech/
    - https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910
    - https://www.theguardian.com/uk/technology/rss
    - https://techcrunch.com/feed/
    - https://arstechnica.com/feed/
    - https://www.wired.com/feed/rss
    - https://www.zdnet.com/news/rss.xml
    - https://www.theregister.com/headlines.rss
    - https://restofworld.org/feed/latest/
    - https://www.bleepingcomputer.com/feed/
    - https://feeds.feedburner.com/venturebeat/SZYF
    - https://feeds.bbci.co.uk/news/technology/rss.xml

  products:
    name: "Products"
    description: "Technology products, their reviews and gadgets, including hardware, devices, smartphones, laptops, etc."
    source:
    - url: https://www.techradar.com/rss
      scrape_needed: false
    - url: https://www.engadget.com/rss.xml
      scrape_needed: false
    - url: https://www.tomsguide.com/feeds/all
      scrape_needed: false

  dev:
    name: "Developer"
    description: "Developer, system, and computer related news, including programming, software, tools, etc."
    sources:
    - url: https://blog.jetbrains.com/feed/
      scrape_needed: false
    - url: https://cprss.s3.amazonaws.com/javascriptweekly.com.xml
      scrape_needed: false
    - url: https://cprss.s3.amazonaws.com/nodeweekly.com.xml
      scrape_needed: false
    - https://stackoverflow.blog/feed
    - https://blog.replit.com/feed.xml
    - https://supabase.com/feed.xml
    - url: https://netflixtechblog.com/feed
      scrape_needed: false
    - https://engineering.atspotify.com/feed
    - url: https://github.blog/feed
      scrape_needed: false
    - url: https://www.docker.com/feed
      scrape_needed: false
    - https://www.osnews.com/feed/
    - https://blog.google/products/chrome/rss
    - https://blog.chromium.org/feeds/posts/default

    # Programming Languages, Runtime and Frameworks
    - https://deno.com/feed
    - url: https://bun.sh/rss.xml
      scrape_needed: false
    - https://vercel.com/atom
    - https://astro.build/rss.xml
    - https://nextjs.org/feed.xml
    - https://tailwindcss.com/feeds/feed.xml

  ai:
    name: AI
    description: "Any LLM, AI, or NLP related news."
    sources:
    - https://www.testingcatalog.com/rss
    - https://stability.ai/news?format=rss
    - https://replicate.com/blog/rss
    - https://jina.ai/feed.rss
    - https://huggingface.co/blog/feed.xml
    - https://deepmind.google/blog/rss.xml
    - https://qwenlm.github.io/blog/index.xml
    - https://blog.google/products/gemini/rss

  software:
    name: "Software"
    description: "Software updates, OS updates, and any software related news."
    sources:
    - url: https://feeds.macrumors.com/MacRumors-All
      scrape_needed: false
    - url: https://www.windowslatest.com/feed/
      scrape_needed: false
    - https://9to5mac.com/feed/
    - https://9to5google.com/feed/
    - url: https://blogs.windows.com/feed
      scrape_needed: false

  hong-kong:
    name: "Hong Kong"
    sources:
    - https://www.scmp.com/rss/2/feed
    - url: https://hongkongfp.com/feed/
      scrape_needed: false
    description: "Hong Kong local news"
