name = "news-bot"
main = "src/index.ts"
compatibility_date = "2024-05-13"

dev.port = 8787

routes = [
	{ pattern = "news-bot.ckt1031.xyz", custom_domain = true }
]

workers_dev = false

[placement]
mode = "smart"

[triggers]
# Schedule cron triggers:
# - At every 5th minute
crons = [ "*/5 * * * *", "0 0 */2 * *" ]

[[d1_databases]]
binding = "D1" # i.e. available in your Worker on env.DB
database_name = "news_bot"
database_id = "d1e122b7-8eab-463e-8e54-f36cc5adcb54"
migrations_dir = ".drizzle"
