name = "news-bot"
main = "src/index.ts"
compatibility_date = "2024-05-13"

dev.port = 8787

routes = [
	{ pattern = "news-bot.tsun1031.xyz", custom_domain = true }
]

workers_dev = false

[triggers]
crons = [ "0 0 */2 * *" ]
