name: News Check

on:
  workflow_dispatch: 
  schedule:
    - cron: "59 */12 * * *"

jobs:
  news-check:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          TOOLS_API_BASE_URL: ${{ secrets.TOOLS_API_BASE_URL }}

      - name: Run script
        run: bun run --filter jobs news-check
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

          RSSHUB_ACCESS_KEY: ${{ secrets.RSSHUB_ACCESS_KEY }}
          RSSHUB_BASE_URL: ${{ secrets.RSSHUB_BASE_URL }}

          TOOLS_API_BASE_URL: ${{ secrets.TOOLS_API_BASE_URL }}
          TOOLS_API_KEY: ${{ secrets.TOOLS_API_KEY }}

          DEFAULT_SUMMARIZE_MODEL: ${{ secrets.DEFAULT_SUMMARIZE_MODEL }}
          DEFAULT_TRANSLATE_MODEL: ${{ secrets.DEFAULT_TRANSLATE_MODEL }}
          DEFAULT_TITLE_GENERATE_MODEL: ${{ secrets.DEFAULT_TITLE_GENERATE_MODEL }}
          DEFAULT_CHECK_IMPORTANCE_MODEL: ${{ secrets.DEFAULT_CHECK_IMPORTANCE_MODEL }}
