name: Assistance Task

on:
  workflow_dispatch: 
  schedule:
    - cron: "*/30 * * * *"

jobs:
  task:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          bun-download-url: "https://github.com/oven-sh/bun/releases/latest/download/bun-${{runner.os == 'macOS' && 'darwin' || runner.os}}-${{ runner.arch == 'X64' && 'x64' || 'arm64' }}.zip"

      - name: Install Dependencies
        run: |
          bun install
          bun run generate-tool-api-schema
        env:
          TOOLS_API_BASE_URL: ${{ secrets.TOOLS_API_BASE_URL }}

      - name: Run Script
        run: bun scripts/news-check.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          RSSHUB_ACCESS_KEY: ${{ secrets.RSSHUB_ACCESS_KEY }}
          RSSHUB_BASE_URL: ${{ secrets.RSSHUB_BASE_URL }}
          TOOLS_API_BASE_URL: ${{ secrets.TOOLS_API_BASE_URL }}
          TOOLS_API_KEY: ${{ secrets.TOOLS_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_BASE_URL: ${{ secrets.LANGFUSE_BASE_URL }}
