name: Assistance Task

on:
  workflow_dispatch: 
  schedule:
    - cron: "*/35 * * * *"

jobs:
  task:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Script
        run: bun src/scripts/action.ts
        env:
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          DISCORD_RSS_CHANNEL_ID: ${{ secrets.DISCORD_RSS_CHANNEL_ID }}
          TOOLS_API_BASE_URL: ${{ secrets.TOOLS_API_BASE_URL }}
          TOOLS_API_KEY: ${{ secrets.TOOLS_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          WORKER_BASE_URL: ${{ secrets.WORKER_BASE_URL }}
          WORKER_API_KEY: ${{ secrets.WORKER_API_KEY }}
