name: Assistance Task

on:
  workflow_dispatch: 
  schedule:
    - cron: "*/30 * * * *"

jobs:
  task:
    timeout-minutes: 15
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20

      - name: Install dependencies
        run: |
          pnpm install
          pnpm run prebuild
        env:
          TOOLS_API_BASE_URL: ${{ secrets.TOOLS_API_BASE_URL }}

      - name: Run script
        run: NODE=1 pnpm run news-check
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
          RSSHUB_ACCESS_KEY: ${{ secrets.RSSHUB_ACCESS_KEY }}
          RSSHUB_BASE_URL: ${{ secrets.RSSHUB_BASE_URL }}
          TOOLS_API_BASE_URL: ${{ secrets.TOOLS_API_BASE_URL }}
          TOOLS_API_KEY: ${{ secrets.TOOLS_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_BASE_URL: ${{ secrets.LANGFUSE_BASE_URL }}
