name: V2EX Check

on:
  workflow_dispatch: 
  schedule:
    - cron: "15 */3 * * *"

jobs:
  v2ex-check:
    timeout-minutes: 25
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          TOOLS_API_BASE_URL: ${{ secrets.TOOLS_API_BASE_URL }}

      - name: Run script
        run: NODE=1 pnpm dlx tsx scripts/v2ex.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENAI_API_BASE_URL: ${{ secrets.OPENAI_API_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RSSHUB_ACCESS_KEY: ${{ secrets.RSSHUB_ACCESS_KEY }}
          RSSHUB_BASE_URL: ${{ secrets.RSSHUB_BASE_URL }}
          TOOLS_API_BASE_URL: ${{ secrets.TOOLS_API_BASE_URL }}
          TOOLS_API_KEY: ${{ secrets.TOOLS_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_BASE_URL: ${{ secrets.LANGFUSE_BASE_URL }}

          # DEFAULT_SUMMARIZE_MODEL: ${{ secrets.DEFAULT_SUMMARIZE_MODEL }}
          # DEFAULT_TRANSLATE_MODEL: ${{ secrets.DEFAULT_TRANSLATE_MODEL }}
          # DEFAULT_TITLE_GENERATE_MODEL: ${{ secrets.DEFAULT_TITLE_GENERATE_MODEL }}
          # DEFAULT_CHECK_IMPORTANCE_MODEL: ${{ secrets.DEFAULT_CHECK_IMPORTANCE_MODEL }}
          # DEFAULT_SEARCH_QUERY_GENERATE_MODEL: ${{ secrets.DEFAULT_SEARCH_QUERY_GENERATE_MODEL }}
